#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Pack the DEXOREN site for transfer to another computer.

The archive root folder is named `dexoren-site` (brand-consistent) even though
the local working directory still keeps its original folder name.

Excludes regenerable / machine-specific directories:
  node_modules  (deps -> restored with `npm install`)
  .next         (build cache -> regenerated by `npm run dev` / `npm run build`)
  .DS_Store     (macOS junk)
"""
import os, zipfile
from pathlib import Path

SRC = Path("/Users/yiyi/Desktop/shenghanindustrial-site")
OUT = Path("/Users/yiyi/Desktop/DEXOREN-site-source.zip")
ARC_TOP = "dexoren-site"

EXCLUDE_DIRS = {"node_modules", ".next"}
EXCLUDE_FILES = {".DS_Store", "npm-debug.log", "yarn-error.log"}
# legacy safety backups of removed liquid categories — not needed to run the site
# backups appear both as hidden ".bak*" and as "*products.json.bak*" etc.
EXCLUDE_NAME_FRAGMENTS = (".bak",)

if OUT.exists():
    OUT.unlink()

n = 0
skipped = 0
with zipfile.ZipFile(OUT, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as z:
    for root, dirs, files in os.walk(SRC):
        dirs[:] = sorted(d for d in dirs if d not in EXCLUDE_DIRS)
        for f in sorted(files):
            if f in EXCLUDE_FILES or any(frag in f for frag in EXCLUDE_NAME_FRAGMENTS):
                skipped += 1
                continue
            fp = Path(root) / f
            if fp.resolve() == OUT.resolve():
                continue
            try:
                z.write(fp, Path(ARC_TOP) / fp.relative_to(SRC))
                n += 1
            except Exception as e:
                print("  skip", fp, e)
                skipped += 1
            if n % 800 == 0:
                print(f"  packed {n} files...", flush=True)

print(f"\nfiles packed: {n}  skipped: {skipped}")
print(f"output: {OUT}")
print(f"size: {OUT.stat().st_size / 1024 / 1024:.1f} MB")
