# -*- coding: utf-8 -*-
"""French (fr) translations — flat dotted-key map (see apply_locale.py)."""

T = {
    # ── nav ──
    "nav.home": "Accueil",
    "nav.products": "Produits",
    "nav.productCategories": "Toutes les catégories",
    "nav.services": "Services",
    "nav.newArrivals": "Nouveautés",
    "nav.flashDeals": "Ventes flash",
    "nav.promotions": "Promotions",
    "nav.rankings": "Classements",
    "nav.certifications": "Certifications",
    "nav.tradeTerms": "Conditions commerciales",
    "nav.faq": "FAQ",
    "nav.about": "À propos",
    "nav.contact": "Contact",
    "nav.call": "WhatsApp",

    # ── hero ──
    "hero.title": "Votre partenaire unique en articles de maison et produits généraux",
    "hero.subtitle": "Prix direct usine, logistique fiable, conformité totale — un partenaire de chaîne d'approvisionnement tout-en-un pour les acheteurs B2B du monde entier.",
    "hero.slide1.tagline": "Fabricant en direct d'usine",
    "hero.slide1.title": "Direct usine",
    "hero.slide1.accent": "Qualité mondiale",
    "hero.slide1.desc": "Meubles, matériaux de construction, quincaillerie, éclairage et produits de nettoyage industriels — fabriqués dans nos propres installations, expédiés dans le monde entier.",
    "hero.slide2.tagline": "Fabrication avancée",
    "hero.slide2.title": "La précision",
    "hero.slide2.accent": "À chaque étape",
    "hero.slide2.desc": "8 lignes de production automatisées fonctionnant 24h/24 avec un contrôle qualité en temps réel, de la matière première au produit fini.",
    "hero.slide3.tagline": "Assurance qualité",
    "hero.slide3.title": "Chaque lot",
    "hero.slide3.accent": "Rigoureusement testé",
    "hero.slide3.desc": "Notre laboratoire accrédité CNAS effectue 12 tests obligatoires par lot — rien n'est expédié sans les avoir réussis.",
    "hero.slide4.tagline": "Portés par l'innovation",
    "hero.slide4.title": "25 ans",
    "hero.slide4.accent": "D'excellence technique",
    "hero.slide4.desc": "Plus de 20 brevets nationaux et une équipe R&D dédiée qui repousse les limites de la technologie des matériaux.",
    "hero.explore": "Découvrir les produits",
    "hero.touch": "Nous contacter",
    "hero.stats.cert": "Certifications",
    "hero.stats.projects": "Projets réalisés",
    "hero.stats.capacity": "Capacité annuelle",
    "hero.overlay.title": "De l'usine à votre projet",
    "hero.overlay.sub": "Direct usine · Prix compétitif · Logistique fiable · Service après-vente mondial",
    "hero.overlay.explore": "Découvrir les solutions",
    "hero.overlay.consult": "Consultation gratuite",

    # ── media ──
    "media.slogan": "Direct usine, portée mondiale",
    "media.desc": "De l'approvisionnement en matières premières à l'inspection finale, chaque étape de notre processus de fabrication est certifiée ISO. Regardez la visite de notre usine pour voir nos installations en action.",
    "media.watch": "Voir la visite d'usine",

    # ── products ──
    "products.searchPrefix": "Recherche : ",
    "products.allCategories": "Toutes les catégories",

    # ── factory ──
    "factory.label": "Notre usine",
    "factory.title": "Une fabrication de pointe",
    "factory.desc": "Notre base de production de 80 000 m² abrite 8 lignes de production automatisées d'une capacité annuelle de 50 000 tonnes. De la synthèse des matières premières à l'emballage du produit fini, chaque étape est contrôlée et surveillée avec précision.",
    "factory.features": [
        "8 lignes de production entièrement automatisées, 24h/24",
        "Laboratoire accrédité CNAS avec plus de 50 instruments de test",
        "Contrôle qualité en temps réel à chaque étape de production",
        "Entrepôt intelligent à température contrôlée",
    ],
    "factory.badge": "ISO 9001",

    # ── quality ──
    "quality.label": "Contrôle qualité",
    "quality.title": "Chaque lot, rigoureusement testé",
    "quality.desc": "Notre laboratoire accrédité CNAS effectue 12 tests obligatoires sur chaque lot de production — de la résistance à la traction et à l'allongement au vieillissement UV et à la résistance chimique. Rien n'est expédié sans les avoir réussis.",
    "quality.features": [
        "12 tests qualité obligatoires par lot de production",
        "Plus de 1 000 heures de simulation de vieillissement accéléré",
        "Traçabilité complète, de la matière première au produit fini",
        "Certification tierce SGS/TÜV disponible",
    ],
    "quality.badge": "Laboratoire CNAS",

    # ── gallery ──
    "gallery.label": "Galerie",
    "gallery.title": "À l'intérieur de notre usine",
    "gallery.desc": "Découvrez nos installations de production de pointe et nos processus de contrôle qualité.",
    "gallery.all": "Tout",
    "gallery.categories": ["Tout", "Usine", "Produits", "Qualité"],
    "gallery.view": "Voir",

    # ── stats ──
    "stats.capacity": "Capacité annuelle",
    "stats.projects": "Projets réalisés",
    "stats.clients": "Clients entreprises",
    "stats.experience": "Expérience sectorielle",
    "stats.unit1": "K tonnes",
    "stats.unit2": "+",
    "stats.unit3": "+",
    "stats.unit4": " ans",

    # ── partners ──
    "partners.prev": "Partenaires précédents",
    "partners.next": "Partenaires suivants",

    # ── cta ──
    "cta.label": "Contact",
    "cta.title": "Obtenez votre solution sur mesure",
    "cta.desc": "Parlez-nous des exigences de votre projet. Notre équipe technique concevra la solution produit optimale pour vous.",

    # ── about ──
    "about.label": "À propos",
    "about.title": "À propos de DEXOREN",
    "about.desc": "Depuis 2002 — d'un fabricant de confiance à une chaîne d'approvisionnement tout-en-un en articles de maison et produits généraux. Showroom de gros de 8 000 m², entrepôt intégré, plus de 30 000 références couvrant la cuisine, le nettoyage, le rangement, le textile, la décoration, les animaux de compagnie et plus encore.",
    "about.storyLabel": "Notre histoire",
    "about.storyTitle1": "Bâtie sur la technologie",
    "about.storyTitle2": "Définie par la qualité",
    "about.storyP1": "Fondée en 2002, DEXOREN est un fabricant complet intégrant la R&D, la production et la distribution mondiale sur cinq gammes de produits principales. Basée à Guangzhou, nous exploitons une installation de production moderne de 80 000 m².",
    "about.storyP2": "Notre laboratoire accrédité CNAS abrite des équipements de test et des instruments de R&D de classe mondiale, soutenus par plus de 20 brevets nationaux. Notre portefeuille couvre les meubles, les adhésifs et mastics pour la construction, l'éclairage LED, la quincaillerie de construction et les solutions de nettoyage industriel.",
    "about.storyP3": "Depuis plus de deux décennies, DEXOREN est portée par l'innovation technologique et définie par la qualité de ses produits — livrant des produits fiables, directement d'usine, à plus de 3 200 clients dans le monde.",
    "about.journeyLabel": "Notre parcours",
    "about.journeyTitle": "Notre parcours",
    "about.journeyDesc": "Plus de deux décennies de progrès constants — chaque étape a été délibérée et résolue.",
    "about.valuesLabel": "Valeurs fondamentales",
    "about.certsLabel": "Certifications",
    "about.tagline": "Nous supprimons la marge de l'intermédiaire, mais conservons les services d'intermédiaire dont vous avez réellement besoin.",
    "about.teamLabel": "Équipe professionnelle",
    "about.teamSubtitle": "Quatre équipes spécialisées couvrant la R&D, le contrôle qualité, le commerce international et la logistique",
    "about.team.title": "Rencontrez notre équipe",
    "about.team.designer": "Designer d'intérieur",
    "about.team.designerDesc": "Crée des plans 2D/3D adaptés à l'esthétique de votre marché local et à votre budget.",
    "about.team.qc": "Ingénieur qualité",
    "about.team.qcDesc": "Contrôle qualité sur toute la chaîne, de la matière première au produit fini. Rapports d'inspection en temps réel.",
    "about.team.supply": "Spécialiste de la chaîne d'approvisionnement",
    "about.team.supplyDesc": "Intègre plus de 100 usines sources. Un seul contact, toutes les catégories couvertes.",
    "about.team.promo": "Responsable de la promotion mondiale",
    "about.team.promoDesc": "Fournit gratuitement du matériel marketing, du contenu pour les réseaux sociaux et une stratégie de promotion pour votre marché.",
    "about.process.title": "Processus 100 % transparent",
    "about.process.desc": "Visites d'usine en vidéo à distance, participation aux inspections en temps réel et accès complet au tableau de bord de votre commande — vous voyez tout ce que nous voyons.",
    "about.timeline": [
        {"year": "2002", "title": "Création de l'entreprise", "desc": "DEXOREN est fondée à Guangzhou, en démarrant comme entreprise de négoce de matériaux de construction."},
        {"year": "2008", "title": "Lancement de la production", "desc": "Mise en service de notre première ligne de fabrication, passant du négoce à la production."},
        {"year": "2013", "title": "Diversification des produits", "desc": "Extension au-delà des matériaux de construction vers le mobilier et la quincaillerie — posant les bases d'un portefeuille multi-catégories."},
        {"year": "2018", "title": "Expansion nationale", "desc": "Construction d'un réseau de vente national servant plus de 300 clients entreprises en Chine."},
        {"year": "2022", "title": "Nouvelles gammes de produits", "desc": "Lancement des gammes d'éclairage LED et de nettoyage industriel, complétant notre offre à cinq catégories."},
        {"year": "2025", "title": "Ouverture à l'international", "desc": "Extension des exportations vers l'Asie du Sud-Est, le Moyen-Orient et l'Afrique — début de notre aventure mondiale."},
    ],
    "about.values": [
        {"title": "Mission", "desc": "Donner aux acheteurs du monde entier accès à des produits de qualité direct usine à des prix compétitifs."},
        {"title": "Vision", "desc": "Devenir un fabricant multi-catégories de classe mondiale et un partenaire d'exportation de confiance."},
        {"title": "Valeurs fondamentales", "desc": "L'intégrité d'abord, la qualité avant tout, portés par l'innovation, collaboration gagnant-gagnant."},
        {"title": "Compétence clé", "desc": "25 ans d'expertise en fabrication, portefeuille multi-catégories, contrôle qualité de bout en bout."},
    ],
    "about.certs": [
        {"title": "ISO 9001:2015", "desc": "Système de management de la qualité"},
        {"title": "ISO 14001:2015", "desc": "Management environnemental"},
        {"title": "Laboratoire CNAS", "desc": "Accréditation nationale chinoise"},
        {"title": "Marquage CE", "desc": "Conformité européenne certifiée"},
    ],
    "about.heroTitle": "Chaîne d'approvisionnement tout-en-un en articles de maison et produits généraux",
    "about.heroSubtitle": "Intégrant la R&D, la production à grande échelle, la distribution mondiale et les services de chaîne d'approvisionnement",
    "about.positioning": "Positionnement",
    "about.aboutDEXOREN": "À propos de DEXOREN",
    "about.introP1": "DEXOREN a été fondée en 2002 — une marque de fabrication moderne intégrant la R&D, la production à grande échelle, les ventes mondiales et les services de chaîne d'approvisionnement. Exploitant nos propres bases de production, nous livrons des produits direct usine et des solutions intégrées aux importateurs, entrepreneurs, détaillants en chaîne et vendeurs B2B transfrontaliers du monde entier.",
    "about.introP2": "Forts de plus de 20 ans d'expertise, nous défendons la qualité d'abord, la conformité d'abord, l'orientation service et la coopération gagnant-gagnant. Nous ne tirons pas profit d'une marge sur les produits — nous ne facturons que des frais de service standardisés. Aujourd'hui, nous servons des partenaires B2B dans plus de 30 pays.",
    "about.philosophy": "Philosophie",
    "about.beyondLabel": "Au-delà des produits",
    "about.beyondTitle": "9 services à valeur ajoutée pour dynamiser votre entreprise",
    "about.beyondDesc": "De la conception à la logistique — découvrez notre système de services complet",
    "about.viewServices": "Voir tous les services",
    "about.partnership": "Partenariat",
    "about.partnershipTitle": "Devenez notre partenaire stratégique à long terme",
    "about.partnershipDesc": "Que vous soyez un petit détaillant, un vendeur transfrontalier ou un grand groupe d'ingénierie — nous offrons des normes de marque unifiées et des capacités professionnelles en tant que partenaire de chaîne d'approvisionnement mondial de confiance.",
    "about.getInTouch": "Nous contacter",
    "about.compliance": "Conformité",
    "about.complianceSubtitle": "Tous les certificats sont des originaux d'usine, téléchargeables par pays",
    "about.access": "Accès",

    # ── contact ──
    "contact.label": "Contact",
    "contact.title": "Nous contacter",
    "contact.desc": "Nous serions ravis de vous entendre — que vous ayez une question produit ou une demande de partenariat.",
    "contact.call": "WhatsApp",
    "contact.email": "Nous écrire",
    "contact.visit": "Nous rendre visite",
    "contact.hours": "Heures d'ouverture",
    "contact.respond": "Nous répondons sous 24 heures",
    "contact.appointment": "Visites sur rendez-vous",
    "contact.connectLabel": "Suivez-nous",
    "contact.connectTitle": "Suivez notre parcours",
    "contact.connectDesc": "Restez informé de nos derniers lancements de produits, de nos analyses sectorielles et des actualités de l'entreprise sur les réseaux sociaux.",
    "contact.formTitle": "Envoyez-nous un message",
    "contact.faq.label": "FAQ",
    "contact.faq.title": "Questions fréquentes",
    "contact.faq.desc": "Questions courantes sur les produits, les commandes et la logistique",
    "contact.faq.q1": "Quelle est la quantité minimale de commande (MOQ) ?",
    "contact.faq.a1": "La MOQ varie selon le produit. La plupart des articles commencent à 10 unités par modèle. Contactez-nous pour les détails de MOQ d'un produit précis — nous pouvons accepter des commandes d'essai.",
    "contact.faq.q2": "Proposez-vous la personnalisation OEM/ODM ?",
    "contact.faq.a2": "Oui. Nous fournissons des services OEM/ODM complets incluant dimensions, matériaux, couleurs, finitions et marque personnalisés. Notre équipe d'ingénierie travaille selon vos spécifications.",
    "contact.faq.q3": "Quel est le délai de production habituel ?",
    "contact.faq.a3": "Le délai standard est de 25 à 35 jours pour la plupart des produits. Les commandes personnalisées peuvent prendre 35 à 45 jours. Commandes urgentes sur demande.",
    "contact.faq.q4": "Puis-je obtenir des échantillons avant une commande en gros ?",
    "contact.faq.a4": "Oui, des échantillons sont disponibles. Le coût de l'échantillon est remboursable sur votre première commande en gros. Nous expédions via DHL/FedEx/UPS avec suivi.",
    "contact.faq.q5": "Quelles conditions de paiement acceptez-vous ?",
    "contact.faq.a5": "Nous acceptons le virement T/T (30 % d'acompte, 70 % avant expédition), la lettre de crédit à vue et Western Union. Les partenaires de longue date peuvent bénéficier de conditions de crédit.",
    "contact.faq.q6": "Fournissez-vous une assistance logistique et d'expédition ?",
    "contact.faq.a6": "Oui. Nous collaborons avec de grands transitaires et pouvons organiser des expéditions FOB/CIF/DDP dans le monde entier. Optimisation du conteneur incluse.",

    # ── form ──
    "form.name": "Votre nom",
    "form.phone": "Numéro de téléphone",
    "form.email": "Adresse e-mail",
    "form.message": "Parlez-nous de vos besoins...",
    "form.submit": "Envoyer la demande",
    "form.sending": "Envoi...",
    "form.thanks": "Merci pour votre demande",
    "form.reply": "Nous vous répondrons sous 24 heures.",
    "form.again": "Envoyer un autre message",

    # ── footer ──
    "footer.products": "Produits",
    "footer.company": "Entreprise",
    "footer.contact": "Contact",
    "footer.privacy": "Politique de confidentialité",
    "footer.terms": "Conditions d'utilisation",
    "footer.rights": "Tous droits réservés.",
    "footer.needHelp": "Besoin d'aide ?",
    "footer.helpHours": "Réponse rapide — généralement sous 12 h (GMT+8)",
    "footer.productsList.homeMerchandise": "Articles de maison et produits généraux",
    "footer.productsList.furniture": "Mobilier",
    "footer.productsList.buildingMaterials": "Matériaux de construction",
    "footer.productsList.hardware": "Quincaillerie",
    "footer.productsList.appliances": "Électroménager",
    "footer.productsList.lighting": "Éclairage",
    "footer.companyList.about": "À propos de nous",
    "footer.companyList.certs": "Certifications",
    "footer.companyList.tradeTerms": "Conditions commerciales",
    "footer.companyList.faq": "FAQ",
    "footer.companyList.contact": "Contact",

    # ── detail ──
    "detail.trustFactory": "Notre propre usine",
    "detail.trustISO": "Certifié ISO",
    "detail.trustResponse": "Réponse < 24 h",
    "detail.tradeTitle": "Commerce et expédition",
    "detail.tradeMoq": "MOQ",
    "detail.tradeLead": "Délai de production",
    "detail.tradeTerm": "Conditions commerciales",
    "detail.tradePack": "Emballage",
    "detail.tradeCert": "Certifications",
    "detail.tradeBrand": "Marque",
    "detail.tradePrice": "Prix de référence (FOB)",
    "detail.tradePriceNote": "Indicatif uniquement — prix final confirmé sur devis",
    "detail.requestQuote": "Demander un devis",
    "detail.whatsappLabel": "Discuter sur WhatsApp",

    # ── cart ──
    "cart.title": "Liste de demandes",
    "cart.empty": "Votre liste de demandes est vide. Parcourez les produits et ajoutez les articles qui vous intéressent.",
    "cart.quantity": "Qté",
    "cart.category": "Catégorie",
    "cart.inquiryList": "LISTE DE DEMANDES",
    "cart.total": "Total",
    "cart.items": "articles",
    "cart.website": "Site web",
    "cart.copy": "Copier le texte",
    "cart.copied": "Copié",
    "cart.download": "Télécharger",
    "cart.contactChat": "Contactez-nous pour un devis",
    "cart.clearAll": "Tout effacer",
    "cart.submitInquiry": "Envoyer la demande",
    "cart.formName": "Votre nom *",
    "cart.formEmail": "Adresse e-mail *",
    "cart.formMessage": "Remarques supplémentaires (facultatif)",
    "cart.cancel": "Annuler",
    "cart.formPhone": "WhatsApp / Téléphone *",
    "cart.successTitle": "Demande envoyée !",
    "cart.successMsg": "Nous vous répondrons sous 24 heures.",

    # ── cookie ──
    "cookie.title": "Notice sur les cookies",
    "cookie.desc": "Nous utilisons des cookies essentiels pour assurer le bon fonctionnement du site. Aucun cookie de suivi ou publicitaire n'est utilisé sans votre consentement.",
    "cookie.learn": "En savoir plus",
    "cookie.accept": "Accepter et continuer",

    # ── modal ──
    "modal.features": "Caractéristiques",
    "modal.specs": "Spécifications",

    # ── promo ──
    "promo.title": "Vente flash mensuelle",
    "promo.subtitle": "Quantités limitées — jusqu'à épuisement du stock",
    "promo.viewAll": "Voir toutes les offres",
    "promo.limited": "Limité",
    "promo.daysLeft": "Plus que {n} jours",

    # ── bestseller ──
    "bestseller.title": "Meilleures ventes du mois",
    "bestseller.subtitle": "Les plus appréciés des acheteurs du monde entier",
    "bestseller.label": "Sélection",

    # ── home ──
    "home.featured": "En vedette",
    "home.newThisMonth": "Nouveautés du mois",
    "home.topPicks": "Sélection",
    "home.bestSellers": "Meilleures ventes du mois",
    "home.rankedBy7Days": "Classé par volume de ventes sur 7 jours — mis à jour quotidiennement",
    "home.hotRanking": "Meilleures ventes",
    "home.viewAll": "Voir tout",
    "home.backToHome": "Retour à l'accueil",
    "home.selectCategory": "Sélectionnez une catégorie dans la barre latérale",
    "home.noProducts": "Aucun produit disponible",
    "home.moreProducts": "Plus de produits",
    "home.noProductsInCategory": "Aucun produit dans cette catégorie pour le moment",
    "home.allProducts": "Tous les produits",
    "home.search": "Rechercher des produits... Appuyez sur Entrée",
    "home.searchPlaceholder": "Rechercher des produits... Appuyez sur Entrée",
    "home.loadMore": "Charger plus",
    "home.items": "articles",
    "home.all": "Tout",
    "home.customerReviews": "Ce que disent nos clients",
    "home.verifiedBuyer": "Acheteur vérifié",
    "home.reviewRated": "a donné la note de",
    "home.reviewStars": "étoiles",
    "home.valueCards.design.title": "Conception + Sélection",
    "home.valueCards.design.desc": "Consultation gratuite en design d'intérieur et sélection de produits pour votre marché",
    "home.valueCards.quality.title": "Contrôle qualité",
    "home.valueCards.quality.desc": "Inspection d'usine sur toute la chaîne et tests tiers pour chaque lot",
    "home.valueCards.delivery.title": "Livraison tout-en-un",
    "home.valueCards.delivery.desc": "Consolidation multi-catégories, logistique porte-à-porte dans le monde entier",
    "home.trust.countries": "Plus de 30 pays desservis",
    "home.trust.containers": "Plus de 1 200 conteneurs expédiés",
    "home.trust.rating": "Note Google 4,8★",
    "home.trust.clients": "Plus de 3 200 clients dans le monde",

    # ── rankings / promotions ──
    "rankings.suffix": " Top",
    "promotions.daysLeft": "Plus que {n} jours — jusqu'à épuisement du stock",

    # ── common ──
    "common.brand": "DEXOREN",
    "common.slogan": "Chaîne d'approvisionnement en articles de maison et produits généraux | Showroom de 8 000 m² · Plus de 30 000 références",
    "common.search": "Rechercher",
    "common.searchPlaceholder": "Rechercher des produits...",
    "common.backToHome": "Retour à l'accueil",
    "common.noProducts": "Aucun produit disponible",
    "common.noProductsInCategory": "Aucun produit dans cette catégorie pour le moment",
    "common.selectCategory": "Sélectionnez une catégorie dans la barre latérale",
    "common.viewAll": "Voir tout",
    "common.comingSoon": "Bientôt disponible",
    "common.subline": "Direct usine · Prix compétitif · Logistique fiable · Service après-vente mondial",

    # ── search ──
    "search.placeholder": "Rechercher des produits... Appuyez sur Entrée",
    "search.inlinePlaceholder": "Rechercher...",
    "search.button": "Rechercher",
    "search.categoryTag": "Catégorie",
    "search.productTag": "Produit",

    # ── flashDeals / newArrivals ──
    "flashDeals.title": "Vente flash quotidienne",
    "flashDeals.subtitle": "Ouvre à des heures aléatoires, jusqu'à épuisement du stock",
    "flashDeals.tag": "Flash",
    "flashDeals.emptyState": "Ventes flash bientôt disponibles — restez à l'écoute !",
    "newArrivals.title": "Nouveautés 2026",
    "newArrivals.subtitle": "Découvrez nos derniers produits de l'année",
    "newArrivals.emptyState": "Nouveautés bientôt disponibles — revenez plus tard !",

    # ── quickInquiry ──
    "quickInquiry.title": "Demande rapide",
    "quickInquiry.namePlaceholder": "Votre nom",
    "quickInquiry.emailPlaceholder": "Votre e-mail",
    "quickInquiry.phonePlaceholder": "WhatsApp / Téléphone",
    "quickInquiry.submit": "Envoyer la demande",
    "quickInquiry.sending": "Envoi...",
    "quickInquiry.success": "Demande envoyée !",
    "quickInquiry.successMsg": "Nous vous contacterons sous 24 heures",
    "quickInquiry.close": "Fermer",
    "quickInquiry.footerNote": "Nous répondons sous 24 heures",
    "quickInquiry.validationError": "Veuillez renseigner votre nom et votre e-mail",
    "quickInquiry.networkError": "Erreur réseau. Veuillez réessayer.",

    "weeklySold": "Vendus 7 j : ",
    "weeklySoldSuffix": "",

    # ── services ──
    "services.heroLabel": "Au-delà de l'approvisionnement · Un accompagnement complet",
    "services.heroTitle": "Des services à valeur ajoutée complets",
    "services.heroSubtitle": "De la conception à la logistique — neuf modules de services essentiels pour les partenaires B2B mondiaux",
    "services.ctaTitle": "Tous les services sont gratuits pour les clients partenaires",
    "services.ctaDesc": "Nous ne tirons pas profit des services — ils constituent notre avantage concurrentiel. Les neuf services sont gratuits pour les clients partenaires.",
    "services.getStarted": "Commencer",
    "services.browseProducts": "Parcourir les produits",

    # ── certifications ──
    "certifications.heroLabel": "Conformité et confiance",
    "certifications.heroTitle": "Certifications et conformité",
    "certifications.heroSubtitle": "Tous les certificats sont des originaux d'usine et disponibles au téléchargement par pays sur demande. Nous vous aidons à dédouaner et à respecter les exigences réglementaires locales du monde entier.",
    "certifications.introTitle": "Une conformité intégrée pour le commerce mondial",
    "certifications.introDesc": "Chaque produit DEXOREN est soutenu par des certifications reconnues internationalement — pour que vos expéditions passent la douane sans encombre et que vos acheteurs fassent confiance à ce qui est en rayon.",
    "certifications.applicableTo": "S'applique à",
    "certifications.region": "Région",
    "certifications.standard": "Norme",
    "certifications.requestTitle": "Besoin des certificats pour votre marché ?",
    "certifications.requestDesc": "Nous fournissons des copies originales de certificats par pays (PDF) et des rapports de tests tiers (SGS, TÜV, Intertek) pour appuyer vos dédouanements et appels d'offres.",
    "certifications.requestBtn": "Demander les certificats",
    "certifications.downloadNote": "Les certificats sont délivrés par commande et par pays de destination. Indiquez-nous votre marché cible et nous vous enverrons l'ensemble exact de documents dont vous avez besoin.",

    # ── tradeTerms ──
    "tradeTerms.heroLabel": "Comment nous travaillons avec vous",
    "tradeTerms.heroTitle": "Conditions commerciales, paiement et expédition",
    "tradeTerms.heroSubtitle": "Transparent, flexible et prêt pour l'export. Des Incoterms au paiement et à la livraison, tout est conçu pour rendre l'approvisionnement transfrontalier simple et à faible risque.",
    "tradeTerms.incotermsTitle": "Incoterms que nous acceptons",
    "tradeTerms.incotermsSub": "Choisissez le terme de livraison adapté à votre logistique. La plupart des commandes partent en FOB ou CIF depuis les grands ports chinois.",
    "tradeTerms.paymentsLabel": "Sécurisé et flexible",
    "tradeTerms.paymentsTitle": "Moyens de paiement",
    "tradeTerms.paymentsSub": "Des options flexibles et sécurisées pour les commandes de toute taille — d'un simple échantillon à un conteneur complet.",
    "tradeTerms.logisticsLabel": "Livraison partout où vous vendez",
    "tradeTerms.logisticsTitle": "Expédition et logistique",
    "tradeTerms.logisticsSub": "Nous travaillons avec de grands transporteurs et exploitons des entrepôts à l'étranger pour que vos marchandises arrivent à l'heure, où que ce soit.",
    "tradeTerms.factsLabel": "À savoir avant de commander",
    "tradeTerms.factsTitle": "Informations essentielles sur la commande",
    "tradeTerms.moqTitle": "Quantité minimale de commande",
    "tradeTerms.moqDesc": "Articles en stock : à partir de 10 pièces par SKU/modèle. OEM et marque propre : 500 à 1 000 pièces par SKU. Plusieurs SKU peuvent être regroupés dans un même conteneur pour réduire votre coût unitaire.",
    "tradeTerms.leadTimeTitle": "Délai de production",
    "tradeTerms.leadTimeDesc": "Produits standards : 25 à 35 jours. Commandes personnalisées/OEM : 35 à 45 jours. Production urgente sur demande.",
    "tradeTerms.sampleTitle": "Échantillons",
    "tradeTerms.sampleDesc": "Des échantillons sont disponibles et expédiés via DHL/FedEx/UPS avec suivi. Le coût de l'échantillon est remboursable sur votre première commande en gros.",
    "tradeTerms.packagingTitle": "Emballage",
    "tradeTerms.packagingDesc": "Cartons d'exportation standards avec calage ; boîtes couleur, codes-barres et palettisation personnalisés disponibles. Palettes et caisses en bois fumigées selon la norme ISPM-15 avec marquage officiel sur demande.",
    "tradeTerms.quoteTitle": "Devis et devise",
    "tradeTerms.quoteDesc": "Les devis sont établis en USD (CNY sur demande) et restent valables 30 jours. Conditions standard : 30 % d'acompte, 70 % de solde contre copie du connaissement.",
    "tradeTerms.complianceLabel": "Qualité, réclamations et conformité",
    "tradeTerms.complianceTitle": "Inspection qualité, réclamations et conformité",
    "tradeTerms.complianceSub": "Comment nous protégeons votre qualité, votre argent et votre accès au marché — avant, pendant et après l'expédition.",
    "tradeTerms.qualityTitle": "Inspection qualité",
    "tradeTerms.qualityDesc": "L'inspection avant expédition par SGS, Bureau Veritas ou Intertek est bienvenue — vous désignez l'inspecteur, ou nous le coordonnons. Si le taux de défauts dépasse l'AQL convenu, nous refabriquons ou créditons les unités concernées.",
    "tradeTerms.claimsTitle": "Réclamations et service après-vente",
    "tradeTerms.claimsDesc": "Signalez tout manquant, dommage ou erreur d'expédition dans les 7 jours suivant l'arrivée, avec photos ou vidéos à l'appui. Nous réglons les réclamations valides par remplacement, avoir sur votre prochaine commande ou remboursement, au cas par cas.",
    "tradeTerms.certTitle": "Certifications et conformité",
    "tradeTerms.certDesc": "Nous accompagnons la conformité du marché de destination : SASO (Arabie saoudite), ESMA (Émirats arabes unis), PVOC (Kenya), SONCAP (Nigeria) et inspection avant expédition COC, ainsi que FDA / LFGB / UE 1935/2004 pour les articles au contact des denrées. Coût et délai selon le produit.",
    "tradeTerms.oemTitle": "OEM et marque propre",
    "tradeTerms.oemDesc": "Logo, couleur, emballage et codes-barres personnalisés à partir de 500 à 1 000 pièces par SKU. Nous gérons les maquettes, les outillages et la conception du carton d'exportation, avec approbation d'échantillon avant la production en série.",
    "tradeTerms.ctaTitle": "Prêt à discuter de votre commande ?",
    "tradeTerms.ctaDesc": "Indiquez-nous votre marché cible, vos produits et vos quantités — nous vous proposerons le meilleur Incoterm, le meilleur échéancier de paiement et la meilleure route d'expédition.",
    "tradeTerms.ctaBtn": "Contacter notre équipe",
    "tradeTerms.catalogBtn": "Demander le catalogue (PDF)",

    # ── faqPage ──
    "faqPage.heroLabel": "Assistance aux acheteurs",
    "faqPage.heroTitle": "Vos questions, nos réponses",
    "faqPage.heroSubtitle": "Tout ce que les acheteurs B2B demandent habituellement sur la MOQ, les prix, les échantillons, la conformité et l'expédition — avant de passer leur première commande.",
    "faqPage.linkCerts": "Certifications",
    "faqPage.linkCertsDesc": "Documents de conformité que nous pouvons délivrer par commande",
    "faqPage.linkTrade": "Conditions commerciales",
    "faqPage.linkTradeDesc": "Incoterms, moyens de paiement et délais de production",
    "faqPage.ctaTitle": "Encore une question ?",
    "faqPage.ctaDesc": "Écrivez-nous sur WhatsApp ou envoyez une demande — notre équipe export répond sous 24 heures.",
}
