# -*- coding: utf-8 -*-
"""Malay (ms / Bahasa Melayu) translations — flat dotted-key map (see apply_locale.py)."""

T = {
    # ── nav ──
    "nav.home": "Utama",
    "nav.products": "Produk",
    "nav.productCategories": "Semua Kategori",
    "nav.services": "Perkhidmatan",
    "nav.newArrivals": "Produk Baharu",
    "nav.flashDeals": "Jualan Kilat",
    "nav.promotions": "Promosi",
    "nav.rankings": "Kedudukan Teratas",
    "nav.certifications": "Pensijilan",
    "nav.tradeTerms": "Terma Perdagangan",
    "nav.faq": "Soalan Lazim",
    "nav.about": "Tentang Kami",
    "nav.contact": "Hubungi Kami",
    "nav.call": "WhatsApp",

    # ── hero ──
    "hero.title": "Rakan Kongsi Sehenti Anda untuk Barangan Rumah & Keperluan Am",
    "hero.subtitle": "Harga terus dari kilang, logistik yang boleh dipercayai, pematuhan penuh — rakan kongsi rantaian bekalan sehenti untuk pembeli B2B di seluruh dunia.",
    "hero.slide1.tagline": "Pengilang Terus dari Kilang",
    "hero.slide1.title": "Terus dari Kilang",
    "hero.slide1.accent": "Kualiti Global",
    "hero.slide1.desc": "Perabot, bahan binaan, perkakasan, pencahayaan dan produk pembersihan industri — dikeluarkan di kemudahan kami sendiri, dihantar ke seluruh dunia.",
    "hero.slide2.tagline": "Pembuatan Termaju",
    "hero.slide2.title": "Ketepatan",
    "hero.slide2.accent": "Di Setiap Peringkat",
    "hero.slide2.desc": "8 barisan pengeluaran automatik beroperasi 24/7 dengan pemantauan kualiti masa nyata dari bahan mentah hingga produk siap.",
    "hero.slide3.tagline": "Jaminan Kualiti",
    "hero.slide3.title": "Setiap Kelompok",
    "hero.slide3.accent": "Diuji Dengan Ketat",
    "hero.slide3.desc": "Makmal bertauliah CNAS menjalankan 12 ujian wajib bagi setiap kelompok — tiada produk dihantar tanpa lulus ujian.",
    "hero.slide4.tagline": "Didorong Inovasi",
    "hero.slide4.title": "25 Tahun",
    "hero.slide4.accent": "Kecemerlangan Teknikal",
    "hero.slide4.desc": "Lebih 20 paten kebangsaan dan pasukan R&D yang berdedikasi terus mengembangkan batasan teknologi bahan.",
    "hero.explore": "Terokai Produk",
    "hero.touch": "Hubungi Kami",
    "hero.stats.cert": "Pensijilan",
    "hero.stats.projects": "Projek Siap",
    "hero.stats.capacity": "Kapasiti Tahunan",
    "hero.overlay.title": "Dari Kilang ke Projek Anda",
    "hero.overlay.sub": "Terus dari Kilang · Harga Kompetitif · Logistik Boleh Dipercayai · Sokongan Selepas Jualan Global",
    "hero.overlay.explore": "Terokai Penyelesaian",
    "hero.overlay.consult": "Konsultasi Percuma",

    # ── media ──
    "media.slogan": "Terus dari Kilang, Capaian Global",
    "media.desc": "Dari pemerolehan bahan mentah hingga pemeriksaan akhir, setiap langkah proses pembuatan kami diperakui ISO. Tonton lawatan kilang kami untuk melihat kemudahan pengeluaran kami beroperasi.",
    "media.watch": "Tonton Lawatan Kilang",

    # ── products ──
    "products.searchPrefix": "Cari: ",
    "products.allCategories": "Semua Kategori",

    # ── factory ──
    "factory.label": "Kilang Kami",
    "factory.title": "Pembuatan Bertaraf Tinggi",
    "factory.desc": "Pangkalan pengeluaran seluas 80,000 m² kami menempatkan 8 barisan pengeluaran automatik dengan kapasiti tahunan 50,000 tan. Dari sintesis bahan mentah hingga pembungkusan produk siap, setiap langkah dikawal dan dipantau dengan tepat.",
    "factory.features": [
        "8 barisan pengeluaran automatik sepenuhnya beroperasi 24/7",
        "Makmal bertauliah CNAS dengan lebih 50 instrumen ujian",
        "Pemantauan kualiti masa nyata di setiap peringkat pengeluaran",
        "Gudang pintar dengan kawalan suhu",
    ],
    "factory.badge": "ISO 9001",

    # ── quality ──
    "quality.label": "Kawalan Kualiti",
    "quality.title": "Setiap Kelompok, Diuji Dengan Ketat",
    "quality.desc": "Makmal bertauliah CNAS kami menjalankan 12 ujian wajib ke atas setiap kelompok pengeluaran — dari kekuatan tegangan dan pemanjangan hingga penuaan UV dan ketahanan kimia. Tiada produk dihantar tanpa lulus ujian.",
    "quality.features": [
        "12 ujian kualiti wajib bagi setiap kelompok pengeluaran",
        "Lebih 1,000 jam simulasi penuaan dipercepatkan",
        "Kebolehkesanan penuh dari bahan mentah hingga produk siap",
        "Pensijilan pihak ketiga SGS/TÜV tersedia",
    ],
    "quality.badge": "Makmal CNAS",

    # ── gallery ──
    "gallery.label": "Galeri",
    "gallery.title": "Di Dalam Kilang Kami",
    "gallery.desc": "Lihat kemudahan pengeluaran bertaraf tinggi dan proses kawalan kualiti kami.",
    "gallery.all": "Semua",
    "gallery.categories": ["Semua", "Kilang", "Produk", "Kualiti"],
    "gallery.view": "Lihat",

    # ── stats ──
    "stats.capacity": "Kapasiti Tahunan",
    "stats.projects": "Projek Siap",
    "stats.clients": "Pelanggan Korporat",
    "stats.experience": "Pengalaman Industri",
    "stats.unit1": "Ribu tan",
    "stats.unit2": "+",
    "stats.unit3": "+",
    "stats.unit4": " tahun",

    # ── partners ──
    "partners.prev": "Rakan kongsi sebelumnya",
    "partners.next": "Rakan kongsi seterusnya",

    # ── cta ──
    "cta.label": "Hubungi",
    "cta.title": "Dapatkan Penyelesaian Tersuai Anda",
    "cta.desc": "Beritahu kami keperluan projek anda. Pasukan teknikal kami akan mereka bentuk penyelesaian produk yang paling sesuai untuk anda.",

    # ── about ──
    "about.label": "Tentang Kami",
    "about.title": "Tentang DEXOREN",
    "about.desc": "Sejak 2002 — daripada pengilang yang dipercayai kepada rantaian bekalan sehenti bagi barangan rumah dan keperluan am. Bilik pameran borong 8,000 m², gudang bersepadu, lebih 30,000 SKU merangkumi dapur, pembersihan, penyimpanan, tekstil, hiasan, haiwan peliharaan dan banyak lagi.",
    "about.storyLabel": "Kisah Kami",
    "about.storyTitle1": "Dibina Atas Teknologi",
    "about.storyTitle2": "Ditakrifkan oleh Kualiti",
    "about.storyP1": "Ditubuhkan pada 2002, DEXOREN ialah pengilang komprehensif yang mengintegrasikan R&D, pembuatan dan pengedaran global merentasi lima barisan produk teras. Beribu pejabat di Guangzhou, kami mengendalikan kemudahan pengeluaran moden seluas 80,000 m².",
    "about.storyP2": "Makmal bertauliah CNAS kami menempatkan peralatan ujian dan instrumentasi R&D bertaraf dunia, disokong oleh lebih 20 paten kebangsaan. Portfolio produk kami merangkumi perabot, pelekat & sealant binaan, pencahayaan LED, perkakasan pembinaan dan penyelesaian pembersihan industri.",
    "about.storyP3": "Selama lebih dua dekad, DEXOREN didorong oleh inovasi teknologi dan ditakrifkan oleh kualiti produk — menghantar produk terus dari kilang yang boleh dipercayai kepada lebih 3,200 pelanggan di seluruh dunia.",
    "about.journeyLabel": "Perjalanan Kami",
    "about.journeyTitle": "Perjalanan Kami",
    "about.journeyDesc": "Lebih dua dekad kemajuan yang berterusan — setiap langkah penuh tujuan dan keteguhan.",
    "about.valuesLabel": "Nilai Teras",
    "about.certsLabel": "Pensijilan",
    "about.tagline": "Kami menghapuskan markup orang tengah, tetapi mengekalkan perkhidmatan orang tengah yang anda benar-benar perlukan.",
    "about.teamLabel": "Pasukan Profesional",
    "about.teamSubtitle": "Empat pasukan khusus merangkumi R&D, kawalan kualiti, perniagaan global dan logistik",
    "about.team.title": "Kenali Pasukan Kami",
    "about.team.designer": "Pereka Dalaman",
    "about.team.designerDesc": "Menghasilkan pelan reka bentuk 2D/3D yang disesuaikan dengan citarasa pasaran tempatan dan bajet anda.",
    "about.team.qc": "Jurutera Kawalan Kualiti",
    "about.team.qcDesc": "Pemantauan kualiti seluruh rantaian dari bahan mentah hingga produk siap. Laporan pemeriksaan masa nyata.",
    "about.team.supply": "Pakar Rantaian Bekalan",
    "about.team.supplyDesc": "Mengintegrasikan lebih 100 kilang sumber. Satu hubungan, semua kategori diliputi.",
    "about.team.promo": "Ketua Promosi Global",
    "about.team.promoDesc": "Menyediakan bahan pemasaran, kandungan media sosial dan strategi promosi percuma untuk pasaran anda.",
    "about.process.title": "Proses 100% Telus",
    "about.process.desc": "Lawatan kilang melalui video jarak jauh, penyertaan pemeriksaan masa nyata, dan akses penuh ke papan pemuka pesanan anda — anda melihat semua yang kami lihat.",
    "about.timeline": [
        {"year": "2002", "title": "Syarikat Ditubuhkan", "desc": "DEXOREN ditubuhkan di Guangzhou, bermula sebagai perniagaan perdagangan bahan binaan."},
        {"year": "2008", "title": "Pelancaran Pengeluaran", "desc": "Mentauliahkan barisan pembuatan pertama kami, beralih daripada perdagangan kepada pengeluaran."},
        {"year": "2013", "title": "Peluasan Produk", "desc": "Berkembang melangkaui bahan binaan kepada perabot dan perkakasan — meletakkan asas bagi portfolio pelbagai kategori."},
        {"year": "2018", "title": "Pengembangan Nasional", "desc": "Membina rangkaian jualan seluruh negara yang berkhidmat kepada lebih 300 pelanggan korporat di China."},
        {"year": "2022", "title": "Barisan Produk Baharu", "desc": "Melancarkan barisan pencahayaan LED dan produk pembersihan industri, melengkapkan lima kategori kami."},
        {"year": "2025", "title": "Ke Pasaran Global", "desc": "Mengembangkan eksport ke Asia Tenggara, Timur Tengah dan Afrika — memulakan perjalanan global kami."},
    ],
    "about.values": [
        {"title": "Misi", "desc": "Memperkasakan pembeli global dengan produk berkualiti terus dari kilang pada harga yang kompetitif."},
        {"title": "Visi", "desc": "Menjadi pengilang pelbagai kategori bertaraf dunia dan rakan kongsi eksport yang dipercayai."},
        {"title": "Nilai Teras", "desc": "Integriti diutamakan, kualiti sebagai keutamaan, didorong inovasi, kerjasama menang-menang."},
        {"title": "Kecekapan Teras", "desc": "25 tahun kepakaran pembuatan, portfolio produk pelbagai kategori, kawalan kualiti menyeluruh."},
    ],
    "about.certs": [
        {"title": "ISO 9001:2015", "desc": "Sistem Pengurusan Kualiti"},
        {"title": "ISO 14001:2015", "desc": "Pengurusan Alam Sekitar"},
        {"title": "Makmal CNAS", "desc": "Akreditasi Kebangsaan China"},
        {"title": "Penandaan CE", "desc": "Pematuhan Eropah Diperakui"},
    ],
    "about.heroTitle": "Rantaian Bekalan Sehenti Barangan Rumah & Keperluan Am",
    "about.heroSubtitle": "Mengintegrasikan R&D, pengeluaran berskala besar, pengedaran global dan perkhidmatan rantaian bekalan",
    "about.positioning": "Kedudukan",
    "about.aboutDEXOREN": "Tentang DEXOREN",
    "about.introP1": "DEXOREN ditubuhkan pada 2002 — jenama pembuatan moden yang mengintegrasikan R&D, pengeluaran berskala besar, jualan global dan perkhidmatan rantaian bekalan. Dengan mengendalikan pangkalan pengeluaran sendiri, kami menghantar produk terus dari kilang dan penyelesaian bersepadu kepada pengimport, kontraktor, peruncit rangkaian dan penjual B2B rentas sempadan di seluruh dunia.",
    "about.introP2": "Dengan kepakaran lebih 20 tahun, kami memegang teguh Kualiti Diutamakan, Pematuhan Diutamakan, Berorientasikan Perkhidmatan dan Kerjasama Menang-Menang. Kami tidak mengaut untung daripada markup produk — kami hanya mengenakan yuran perkhidmatan piawai. Kini kami berkhidmat kepada rakan kongsi B2B di lebih 30 negara.",
    "about.philosophy": "Falsafah",
    "about.beyondLabel": "Melangkaui Produk",
    "about.beyondTitle": "9 Perkhidmatan Nilai Tambah Untuk Memperkasa Perniagaan Anda",
    "about.beyondDesc": "Dari reka bentuk hingga logistik — terokai sistem perkhidmatan lengkap kami",
    "about.viewServices": "Lihat Semua Perkhidmatan",
    "about.partnership": "Perkongsian",
    "about.partnershipTitle": "Jadilah Rakan Kongsi Strategik Jangka Panjang Kami",
    "about.partnershipDesc": "Sama ada peruncit kecil, penjual rentas sempadan atau kumpulan kejuruteraan besar — kami menyediakan piawaian jenama yang seragam dan keupayaan profesional sebagai rakan kongsi rantaian bekalan global anda yang dipercayai.",
    "about.getInTouch": "Hubungi Kami",
    "about.compliance": "Pematuhan",
    "about.complianceSubtitle": "Semua sijil adalah asli dari kilang, tersedia untuk dimuat turun mengikut negara",
    "about.access": "Akses",

    # ── contact ──
    "contact.label": "Hubungi",
    "contact.title": "Hubungi Kami",
    "contact.desc": "Kami sudi mendengar daripada anda — sama ada anda ada soalan tentang produk atau pertanyaan kerjasama.",
    "contact.call": "WhatsApp",
    "contact.email": "E-mel Kami",
    "contact.visit": "Lawati Kami",
    "contact.hours": "Waktu Perniagaan",
    "contact.respond": "Kami membalas dalam masa 24 jam",
    "contact.appointment": "Lawatan dengan temu janji",
    "contact.connectLabel": "Berhubung Dengan Kami",
    "contact.connectTitle": "Ikuti Perjalanan Kami",
    "contact.connectDesc": "Dapatkan kemas kini pelancaran produk terkini, pandangan industri dan berita syarikat kami di media sosial.",
    "contact.formTitle": "Hantar Mesej Kepada Kami",
    "contact.faq.label": "Soalan Lazim",
    "contact.faq.title": "Soalan Lazim",
    "contact.faq.desc": "Soalan biasa tentang produk, pesanan dan logistik",
    "contact.faq.q1": "Berapakah kuantiti pesanan minimum (MOQ)?",
    "contact.faq.a1": "MOQ berbeza mengikut produk. Kebanyakan item bermula dari 10 unit setiap rekaan. Hubungi kami untuk butiran MOQ produk tertentu — kami boleh mempertimbangkan pesanan percubaan.",
    "contact.faq.q2": "Adakah anda menawarkan penyesuaian OEM/ODM?",
    "contact.faq.a2": "Ya. Kami menyediakan perkhidmatan OEM/ODM penuh termasuk dimensi, bahan, warna, kemasan dan penjenamaan tersuai. Pasukan kejuruteraan kami bekerja mengikut spesifikasi anda.",
    "contact.faq.q3": "Berapakah tempoh masa penghantaran biasa?",
    "contact.faq.a3": "Tempoh standard ialah 25–35 hari untuk kebanyakan produk. Pesanan tersuai mungkin mengambil masa 35–45 hari. Pesanan segera tersedia atas permintaan.",
    "contact.faq.q4": "Bolehkah saya mendapatkan sampel sebelum pesanan pukal?",
    "contact.faq.a4": "Ya, sampel tersedia. Kos sampel boleh dikembalikan dengan pesanan pukal pertama anda. Kami menghantar melalui DHL/FedEx/UPS dengan penjejakan.",
    "contact.faq.q5": "Apakah terma pembayaran yang anda terima?",
    "contact.faq.a5": "Kami menerima T/T (deposit 30%, baki 70% sebelum penghantaran), L/C pada pandangan, dan Western Union. Rakan kongsi jangka panjang mungkin layak untuk terma kredit.",
    "contact.faq.q6": "Adakah anda menyediakan sokongan logistik dan penghantaran?",
    "contact.faq.a6": "Ya. Kami mempunyai kerjasama dengan penghantar barang utama dan boleh mengatur penghantaran FOB/CIF/DDP ke seluruh dunia. Pengoptimuman kontena disertakan.",

    # ── form ──
    "form.name": "Nama Anda",
    "form.phone": "Nombor Telefon",
    "form.email": "Alamat E-mel",
    "form.message": "Beritahu kami keperluan anda...",
    "form.submit": "Hantar Pertanyaan",
    "form.sending": "Menghantar...",
    "form.thanks": "Terima Kasih Atas Pertanyaan Anda",
    "form.reply": "Kami akan menghubungi anda kembali dalam masa 24 jam.",
    "form.again": "Hantar mesej lain",

    # ── footer ──
    "footer.products": "Produk",
    "footer.company": "Syarikat",
    "footer.contact": "Hubungi",
    "footer.privacy": "Dasar Privasi",
    "footer.terms": "Terma Perkhidmatan",
    "footer.rights": "Semua hak terpelihara.",
    "footer.needHelp": "Perlukan bantuan?",
    "footer.helpHours": "Balasan pantas — biasanya dalam 12 jam (GMT+8)",
    "footer.productsList.homeMerchandise": "Barangan Rumah & Keperluan Am",
    "footer.productsList.furniture": "Perabot",
    "footer.productsList.buildingMaterials": "Bahan Binaan",
    "footer.productsList.hardware": "Perkakasan",
    "footer.productsList.appliances": "Peralatan Elektrik",
    "footer.productsList.lighting": "Pencahayaan",
    "footer.companyList.about": "Tentang Kami",
    "footer.companyList.certs": "Pensijilan",
    "footer.companyList.tradeTerms": "Terma Perdagangan",
    "footer.companyList.faq": "Soalan Lazim",
    "footer.companyList.contact": "Hubungi Kami",

    # ── detail ──
    "detail.trustFactory": "Kilang Sendiri",
    "detail.trustISO": "Diperakui ISO",
    "detail.trustResponse": "Balas < 24 jam",
    "detail.tradeTitle": "Perdagangan & Penghantaran",
    "detail.tradeMoq": "MOQ",
    "detail.tradeLead": "Tempoh Pengeluaran",
    "detail.tradeTerm": "Terma Perdagangan",
    "detail.tradePack": "Pembungkusan",
    "detail.tradeCert": "Pensijilan",
    "detail.tradeBrand": "Jenama",
    "detail.tradePrice": "Harga Rujukan (FOB)",
    "detail.tradePriceNote": "Anggaran sahaja — harga akhir disahkan pada sebut harga",
    "detail.requestQuote": "Minta Sebut Harga",
    "detail.whatsappLabel": "Sembang di WhatsApp",

    # ── cart ──
    "cart.title": "Senarai Pertanyaan",
    "cart.empty": "Senarai pertanyaan anda kosong. Semak imbas produk dan tambah item yang anda minati.",
    "cart.quantity": "Kuantiti",
    "cart.category": "Kategori",
    "cart.inquiryList": "SENARAI PERTANYAAN",
    "cart.total": "Jumlah",
    "cart.items": "item",
    "cart.website": "Laman web",
    "cart.copy": "Salin Teks",
    "cart.copied": "Disalin",
    "cart.download": "Muat Turun",
    "cart.contactChat": "Hubungi Kami Untuk Sebut Harga",
    "cart.clearAll": "Kosongkan Semua",
    "cart.submitInquiry": "Hantar Pertanyaan",
    "cart.formName": "Nama Anda *",
    "cart.formEmail": "Alamat E-mel *",
    "cart.formMessage": "Catatan tambahan (pilihan)",
    "cart.cancel": "Batal",
    "cart.formPhone": "WhatsApp / Telefon *",
    "cart.successTitle": "Pertanyaan Dihantar!",
    "cart.successMsg": "Kami akan membalas dalam masa 24 jam.",

    # ── cookie ──
    "cookie.title": "Notis Kuki",
    "cookie.desc": "Kami menggunakan kuki penting untuk memastikan laman web berfungsi dengan baik. Tiada kuki penjejakan atau pengiklanan digunakan tanpa persetujuan anda.",
    "cookie.learn": "Ketahui lebih lanjut",
    "cookie.accept": "Terima & Teruskan",

    # ── modal ──
    "modal.features": "Ciri-ciri",
    "modal.specs": "Spesifikasi",

    # ── promo ──
    "promo.title": "Jualan Kilat Bulanan",
    "promo.subtitle": "Kuantiti terhad — selagi stok masih ada",
    "promo.viewAll": "Lihat Semua Tawaran",
    "promo.limited": "Terhad",
    "promo.daysLeft": "Tinggal {n} hari lagi",

    # ── bestseller ──
    "bestseller.title": "Produk Terlaris Bulanan",
    "bestseller.subtitle": "Paling digemari pembeli global",
    "bestseller.label": "Pilihan Utama",

    # ── home ──
    "home.featured": "Pilihan",
    "home.newThisMonth": "Baharu Bulan Ini",
    "home.topPicks": "Pilihan Utama",
    "home.bestSellers": "Produk Terlaris Bulanan",
    "home.rankedBy7Days": "Disusun mengikut jumlah jualan 7 hari — dikemas kini setiap hari",
    "home.hotRanking": "Terlaris",
    "home.viewAll": "Lihat Semua",
    "home.backToHome": "Kembali ke Utama",
    "home.selectCategory": "Pilih kategori dari bar sisi",
    "home.noProducts": "Tiada produk tersedia",
    "home.moreProducts": "Lebih Banyak Produk",
    "home.noProductsInCategory": "Belum ada produk dalam kategori ini",
    "home.allProducts": "Semua Produk",
    "home.search": "Cari produk... Tekan Enter",
    "home.searchPlaceholder": "Cari produk... Tekan Enter",
    "home.loadMore": "Muat Lebih Banyak",
    "home.items": "item",
    "home.all": "Semua",
    "home.customerReviews": "Kata Pelanggan Kami",
    "home.verifiedBuyer": "Pembeli Disahkan",
    "home.reviewRated": "memberi penarafan",
    "home.reviewStars": "bintang",
    "home.valueCards.design.title": "Reka Bentuk + Pemilihan",
    "home.valueCards.design.desc": "Konsultasi reka bentuk dalaman dan padanan produk percuma untuk pasaran anda",
    "home.valueCards.quality.title": "Kawalan Kualiti",
    "home.valueCards.quality.desc": "Pemeriksaan kilang seluruh rantaian dan ujian pihak ketiga bagi setiap kelompok",
    "home.valueCards.delivery.title": "Penghantaran Sehenti",
    "home.valueCards.delivery.desc": "Penggabungan pelbagai kategori, logistik dari pintu ke pintu ke seluruh dunia",
    "home.trust.countries": "30+ Negara Dilayan",
    "home.trust.containers": "1,200+ Kontena Dihantar",
    "home.trust.rating": "Penarafan Google 4.8★",
    "home.trust.clients": "3,200+ Pelanggan Seluruh Dunia",

    # ── rankings / promotions ──
    "rankings.suffix": " Teratas",
    "promotions.daysLeft": "Tinggal {n} hari lagi — selagi stok masih ada",

    # ── common ──
    "common.brand": "DEXOREN",
    "common.slogan": "Rantaian Bekalan Barangan Rumah & Keperluan Am | Bilik Pameran 8,000 m² · 30,000+ SKU",
    "common.search": "Cari",
    "common.searchPlaceholder": "Cari produk...",
    "common.backToHome": "Kembali ke Utama",
    "common.noProducts": "Tiada produk tersedia",
    "common.noProductsInCategory": "Belum ada produk dalam kategori ini",
    "common.selectCategory": "Pilih kategori dari bar sisi",
    "common.viewAll": "Lihat semua",
    "common.comingSoon": "Akan datang",
    "common.subline": "Terus dari Kilang · Harga Kompetitif · Logistik Boleh Dipercayai · Sokongan Selepas Jualan Global",

    # ── search ──
    "search.placeholder": "Cari produk... Tekan Enter",
    "search.inlinePlaceholder": "Cari...",
    "search.button": "Cari",
    "search.categoryTag": "Kategori",
    "search.productTag": "Produk",

    # ── flashDeals / newArrivals ──
    "flashDeals.title": "Jualan Kilat Harian",
    "flashDeals.subtitle": "Dibuka pada masa rawak, selagi stok masih ada",
    "flashDeals.tag": "Kilat",
    "flashDeals.emptyState": "Jualan kilat akan datang — nantikan!",
    "newArrivals.title": "Produk Baharu 2026",
    "newArrivals.subtitle": "Temui produk terbaharu kami tahun ini",
    "newArrivals.emptyState": "Produk baharu akan datang — semak semula nanti!",

    # ── quickInquiry ──
    "quickInquiry.title": "Pertanyaan Pantas",
    "quickInquiry.namePlaceholder": "Nama Anda",
    "quickInquiry.emailPlaceholder": "E-mel Anda",
    "quickInquiry.phonePlaceholder": "WhatsApp / Telefon",
    "quickInquiry.submit": "Hantar Pertanyaan",
    "quickInquiry.sending": "Menghantar...",
    "quickInquiry.success": "Pertanyaan Dihantar!",
    "quickInquiry.successMsg": "Kami akan menghubungi anda dalam masa 24 jam",
    "quickInquiry.close": "Tutup",
    "quickInquiry.footerNote": "Kami membalas dalam masa 24 jam",
    "quickInquiry.validationError": "Sila isi nama dan e-mel anda",
    "quickInquiry.networkError": "Ralat rangkaian. Sila cuba semula.",

    "weeklySold": "Terjual 7h: ",
    "weeklySoldSuffix": "",

    # ── services ──
    "services.heroLabel": "Melangkaui Bekalan · Pemerkasaan Penuh",
    "services.heroTitle": "Perkhidmatan Nilai Tambah Yang Menyeluruh",
    "services.heroSubtitle": "Dari reka bentuk hingga logistik — sembilan modul perkhidmatan teras untuk rakan kongsi B2B global",
    "services.ctaTitle": "Semua Perkhidmatan Percuma Untuk Pelanggan Kerjasama",
    "services.ctaDesc": "Kami tidak mengaut untung daripada perkhidmatan — itulah kelebihan daya saing kami. Kesemua sembilan perkhidmatan percuma untuk pelanggan kerjasama.",
    "services.getStarted": "Mulakan",
    "services.browseProducts": "Semak Imbas Produk",

    # ── certifications ──
    "certifications.heroLabel": "Pematuhan & Kepercayaan",
    "certifications.heroTitle": "Pensijilan & Pematuhan",
    "certifications.heroSubtitle": "Semua sijil adalah asli dari kilang dan tersedia untuk dimuat turun mengikut negara atas permintaan. Kami membantu anda melepasi kastam dan memenuhi keperluan peraturan tempatan di seluruh dunia.",
    "certifications.introTitle": "Pematuhan Terbina Untuk Perdagangan Global",
    "certifications.introDesc": "Setiap produk DEXOREN disokong oleh pensijilan yang diiktiraf di peringkat antarabangsa — supaya penghantaran anda melepasi kastam dengan lancar dan pembeli anda mempercayai apa yang ada di rak.",
    "certifications.applicableTo": "Terpakai Untuk",
    "certifications.region": "Wilayah",
    "certifications.standard": "Standard",
    "certifications.requestTitle": "Perlukan Fail Sijil Untuk Pasaran Anda?",
    "certifications.requestDesc": "Kami menyediakan salinan sijil asli mengikut negara (PDF) dan laporan ujian pihak ketiga (SGS, TÜV, Intertek) untuk menyokong pelepasan import dan tender anda.",
    "certifications.requestBtn": "Minta Sijil",
    "certifications.downloadNote": "Sijil dikeluarkan mengikut pesanan dan negara destinasi. Beritahu kami pasaran sasaran anda dan kami akan menghantar set dokumentasi tepat yang anda perlukan.",

    # ── tradeTerms ──
    "tradeTerms.heroLabel": "Cara Kami Bekerja Dengan Anda",
    "tradeTerms.heroTitle": "Terma Perdagangan, Pembayaran & Penghantaran",
    "tradeTerms.heroSubtitle": "Telus, fleksibel dan sedia untuk eksport. Dari Incoterms hingga pembayaran dan penghantaran, semuanya direka untuk menjadikan pemerolehan rentas sempadan mudah dan berisiko rendah.",
    "tradeTerms.incotermsTitle": "Incoterms Yang Kami Sokong",
    "tradeTerms.incotermsSub": "Pilih terma penghantaran yang sesuai dengan susunan logistik anda. Kebanyakan pesanan dihantar secara FOB atau CIF dari pelabuhan utama China.",
    "tradeTerms.paymentsLabel": "Selamat & Fleksibel",
    "tradeTerms.paymentsTitle": "Kaedah Pembayaran",
    "tradeTerms.paymentsSub": "Pilihan yang fleksibel dan selamat untuk pesanan pelbagai saiz — dari satu sampel hingga satu kontena penuh.",
    "tradeTerms.logisticsLabel": "Sampai Ke Mana Anda Berniaga",
    "tradeTerms.logisticsTitle": "Penghantaran & Logistik",
    "tradeTerms.logisticsSub": "Kami bekerjasama dengan pengangkut utama dan mengendalikan gudang luar negara supaya barangan anda tiba tepat pada masanya, di mana sahaja.",
    "tradeTerms.factsLabel": "Perlu Tahu Sebelum Memesan",
    "tradeTerms.factsTitle": "Maklumat Penting Pesanan",
    "tradeTerms.moqTitle": "Kuantiti Pesanan Minimum",
    "tradeTerms.moqDesc": "Item sedia ada: dari 10 keping setiap SKU/rekaan. OEM & jenama sendiri: 500–1,000 keping setiap SKU. Pelbagai SKU boleh digabungkan dalam satu kontena untuk mengurangkan kos seunit anda.",
    "tradeTerms.leadTimeTitle": "Tempoh Pengeluaran",
    "tradeTerms.leadTimeDesc": "Produk standard: 25–35 hari. Pesanan tersuai/OEM: 35–45 hari. Pengeluaran segera tersedia atas permintaan.",
    "tradeTerms.sampleTitle": "Sampel",
    "tradeTerms.sampleDesc": "Sampel tersedia dan dihantar melalui DHL/FedEx/UPS dengan penjejakan. Kos sampel boleh dikembalikan dengan pesanan pukal pertama anda.",
    "tradeTerms.packagingTitle": "Pembungkusan",
    "tradeTerms.packagingDesc": "Karton eksport standard dengan pelapik pelindung; kotak warna tersuai, kod bar dan peletan tersedia. Palet dan peti kayu difumigasi mengikut ISPM-15 dengan penandaan rasmi atas permintaan.",
    "tradeTerms.quoteTitle": "Sebut Harga & Mata Wang",
    "tradeTerms.quoteDesc": "Sebut harga dikeluarkan dalam USD (CNY atas permintaan) dan sah selama 30 hari. Terma standard: deposit 30%, baki 70% terhadap salinan Bil Muatan.",
    "tradeTerms.complianceLabel": "Kualiti, Tuntutan & Pematuhan",
    "tradeTerms.complianceTitle": "Pemeriksaan Kualiti, Tuntutan & Pematuhan",
    "tradeTerms.complianceSub": "Bagaimana kami melindungi kualiti, wang dan akses pasaran anda — sebelum, semasa dan selepas penghantaran.",
    "tradeTerms.qualityTitle": "Pemeriksaan Kualiti",
    "tradeTerms.qualityDesc": "Pemeriksaan pra-penghantaran oleh SGS, Bureau Veritas atau Intertek dialu-alukan — anda melantik pemeriksa, atau kami mengaturnya. Jika kadar kecacatan melebihi AQL yang dipersetujui, kami menggantikan atau mengkreditkan unit yang terjejas.",
    "tradeTerms.claimsTitle": "Tuntutan & Selepas Jualan",
    "tradeTerms.claimsDesc": "Laporkan kekurangan, kerosakan atau salah hantar dalam tempoh 7 hari selepas ketibaan dengan bukti foto atau video. Kami menyelesaikan tuntutan yang sah melalui penggantian, kredit untuk pesanan seterusnya, atau bayaran balik — dipersetujui kes demi kes.",
    "tradeTerms.certTitle": "Pensijilan & Pematuhan",
    "tradeTerms.certDesc": "Kami menyokong pematuhan pasaran destinasi: SASO (Arab Saudi), ESMA (UAE), PVOC (Kenya), SONCAP (Nigeria) dan pemeriksaan pra-penghantaran COC, serta FDA / LFGB / EU 1935/2004 untuk item sentuhan makanan. Kos dan tempoh bergantung pada produk.",
    "tradeTerms.oemTitle": "OEM & Jenama Sendiri",
    "tradeTerms.oemDesc": "Logo, warna, pembungkusan dan kod bar tersuai dari 500–1,000 keping setiap SKU. Kami menguruskan karya seni, acuan dan reka bentuk karton eksport, dengan kelulusan sampel sebelum pengeluaran besar-besaran.",
    "tradeTerms.ctaTitle": "Sedia Untuk Bincangkan Pesanan Anda?",
    "tradeTerms.ctaDesc": "Beritahu kami pasaran sasaran, produk dan kuantiti anda — kami akan mencadangkan Incoterm, pelan pembayaran dan laluan penghantaran yang terbaik.",
    "tradeTerms.ctaBtn": "Hubungi Pasukan Kami",
    "tradeTerms.catalogBtn": "Minta Katalog (PDF)",

    # ── faqPage ──
    "faqPage.heroLabel": "Sokongan Pembeli",
    "faqPage.heroTitle": "Soalan, dijawab",
    "faqPage.heroSubtitle": "Semua yang biasanya ditanya oleh pembeli B2B tentang MOQ, harga, sampel, pematuhan dan penghantaran — sebelum membuat pesanan pertama.",
    "faqPage.linkCerts": "Pensijilan",
    "faqPage.linkCertsDesc": "Dokumen pematuhan yang boleh kami keluarkan mengikut pesanan",
    "faqPage.linkTrade": "Terma Perdagangan",
    "faqPage.linkTradeDesc": "Incoterms, kaedah pembayaran dan tempoh pengeluaran",
    "faqPage.ctaTitle": "Masih ada soalan?",
    "faqPage.ctaDesc": "Mesej kami di WhatsApp atau hantar pertanyaan — pasukan eksport kami membalas dalam masa 24 jam.",
}
